flowchart LR
jx[%jx] --> rt & rs


qs[%qs] --> cl & rs
zr[%zr] --> cq
mx[%mx] --> nr & pm
mj[%mj] --> qr & cc
cj[%cj] --> cc & nt
jv[%jv] --> sp
dj[%dj] --> bd & zc
kt[%kt] --> lt
broadcaster --> gz & xg & cd & sg

br[%br] --> nf & bd
cd[%cd] --> cc & nl
zc[%zc] --> jq & bd
xg[%xg] --> cf & pm
nz[%nz] --> gm & bd

nb[%nb] --> sl

rt[%rt] --> qq
qq[%qq] --> rs & hd
hd[%hd] --> qs & rs

pj[%pj] --> cc & mj
gz[%gz] --> bd & kb
zd[%zd] --> jv & pm
cq[%cq] --> cj & cc
qr[%qr] --> gk
ng[%ng] --> jk & bd
kb[%kb] --> bd & sv
cl[%cl] --> zx & rs
gj[%gj] --> zd & pm
sl[%sl] --> kx
sv[%sv] --> br
nf[%nf] --> bd & nz
zx[%zx] --> rs
nt[%nt] --> mn & cc
rh[%rh] --> nb & rs
gk[%gk] --> ln

jq[%jq] --> ng & bd
sp[%sp] --> pc
sg[%sg] --> rs & rh
kx[%kx] --> jx

cf[%cf] --> gj & pm
pc[%pc] --> kt & pm
jk[%jk] --> bd
vf[%vf] --> pm

nr[%nr] --> vf & pm
ln[%ln] --> zr & cc
lt[%lt] --> pm & mx
gm[%gm] --> dj
nl[%nl] --> pj
mn[%mn] --> cc

broadcaster

subgraph "a4"

sg[%sg]
rh[%rh]
nb[%nb]
sl[%sl]
kx[%kx]
jx[%jx]
rt[%rt]
qq[%qq]
hd[%hd]
qs[%qs]
cl[%cl]
zx[%zx]

end

subgraph "a1"

gz[%gz]
kb[%kb]
sv[%sv]
br[%br]
nf[%nf]
nz[%nz]
gm[%gm]
dj[%dj]
zc[%zc]
jq[%jq]
ng[%ng]
jk[%jk]

end

subgraph "a2"

xg[%xg]
cf[%cf]
gj[%gj]
zd[%zd]
jv[%jv]
sp[%sp]
pc[%pc]
kt[%kt]
lt[%lt]
mx[%mx]
nr[%nr]
vf[%vf]

end

subgraph "a3"

zr[%zr]
mj[%mj]
cj[%cj]
cd[%cd]
pj[%pj]
cq[%cq]
qr[%qr]
nt[%nt]
gk[%gk]
ln[%ln]
nl[%nl]
mn[%mn]

end

subgraph "b"

cc[&cc]
pm[&pm]
bd[&bd]
rs[&rs]

end

subgraph "c"

fh[&fh]
dd[&dd]
dn[&dn]
xp[&xp]
fc[&fc]

end

cc[&cc] --> cd & fc & qr & nl & gk & zr
dn[&dn] --> rx
dd[&dd] --> dn
pm[&pm] --> kt & xg & xp & jv & sp
fh[&fh] --> dn
xp[&xp] --> dn
bd[&bd] --> gm & gz & fh & sv
fc[&fc] --> dn
rs[&rs] --> sg & dd & sl & kx & nb & rt